name: quiz
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.1  # Added shared_preferences for level management
  provider: ^6.0.5            # Optional: For state management if needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/professor.png
    - assets/images/chart.jpeg
